# Generated by Django 4.2.29 on 2026-03-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('mode', models.CharField(default='text', max_length=10)),
                ('tts_provider', models.CharField(default='local', max_length=10)),
            ],
        ),
    ]
