# Generated by Django 4.2.30 on 2026-05-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usersettings_tts_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='tts_provider',
            field=models.CharField(default='edge', max_length=10),
        ),
    ]
