# Generated by Django 4.2.30 on 2026-05-15 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_usersettings_tts_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='auth_user',
            field=models.OneToOneField(blank=True, db_column='auth_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=200)),
                ('farm_size', models.FloatField(blank=True, help_text='Farm size in bigha', null=True)),
                ('primary_crops', models.JSONField(blank=True, default=list)),
                ('soil_type', models.CharField(blank=True, choices=[('alluvial', 'Alluvial (जलोढ़)'), ('clay', 'Clay (चिकनी मिट्टी)'), ('sandy', 'Sandy (बालू मिट्टी)'), ('loamy', 'Loamy (दोमट)'), ('red', 'Red (लाल मिट्टी)'), ('black', 'Black (काली मिट्टी)')], max_length=50)),
                ('irrigation_source', models.CharField(blank=True, choices=[('canal', 'Canal (नहर)'), ('tubewell', 'Tube Well (बोरिंग)'), ('pond', 'Pond (तालाब)'), ('rainfed', 'Rainfed (वर्षा आधारित)'), ('river', 'River (नदी)'), ('well', 'Open Well (कुआं)')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_profile', to='api.usersettings')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.usersettings')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
